import requests
import time

questions = marketing_research_questions = [
    "What are the biggest challenges companies are trying to solve via web scraping in marketing?",
    "How do marketers use web scraping to improve competitive analysis?",
    "What types of customer insights are companies trying to gain through web scraping?",
    "Which marketing KPIs are most influenced by web scraping data?",
    "How do B2B companies use web scraping to identify new leads?",
    "What role does web scraping play in pricing strategy development?",
    "How do marketers ensure data accuracy when using web scraping tools?",
    "What are the most common data sources marketers target with web scraping?",
    "How can web scraping help in understanding consumer sentiment?",
    "What ethical concerns do marketers face when using web scraping techniques?",
    "How does web scraping support SEO and keyword tracking strategies?",
    "What impact does scraped competitor data have on ad campaign optimization?",
    "How can marketers use scraped data to personalize customer experiences?",
    "What industries rely most heavily on web scraping for market research?",
    "How does web scraping assist in tracking brand mentions across the web?",
    "What are the key technical challenges in implementing web scraping at scale?",
    "How do marketing teams handle changes in website structure affecting scrapers?",
    "How does web scraping contribute to real-time market trend analysis?",
    "What are the legal risks of using scraped data for marketing purposes?",
    "How can scraped product reviews inform marketing strategies?",
    "How can web scraping enhance influencer marketing efforts?",
    "What competitive advantages are enabled by web scraping?",
    "How do marketers assess the ROI of web scraping initiatives?",
    "How is web scraping used for audience segmentation?",
    "How can companies identify market gaps using scraped data?",
    "How is scraped social media data used for campaign planning?",
    "What automation tools are commonly paired with web scraping in marketing?",
    "How do marketing teams integrate scraped data with CRM platforms?",
    "How do marketers ensure compliance with data protection regulations when scraping?",
    "How can scraped job postings be used for market intelligence?",
    "What are the best practices for maintaining web scrapers in a marketing context?",
    "How do scraped eCommerce data points shape product positioning?",
    "How is web scraping used in demand forecasting?",
    "How do marketers use web scraping to track competitor promotions?",
    "How can scraped news articles inform brand communication strategy?",
    "How do companies monitor customer reviews across platforms via scraping?",
    "What are the differences between scraping structured vs. unstructured data for marketing?",
    "How does scraped data help identify emerging consumer needs?",
    "How do marketers use scraped location data for regional targeting?",
    "How is scraping used to monitor affiliate marketing performance?",
    "How do marketers prioritize what data to scrape?",
    "How does scraping support content curation strategies?",
    "What impact does real-time data scraping have on marketing agility?",
    "How is scraping integrated into marketing automation workflows?",
    "How do B2C brands use web scraping differently from B2B companies?",
    "How does scraped data influence email marketing strategies?",
    "How is web scraping used to discover trending products?",
    "What is the role of scraping in market entry research?",
    "How do marketers validate scraped data before using it?",
    "How do scraping practices vary across different regions or markets?",
    "How can scraping customer questions from forums support FAQ and content strategy?",
    "How is scraping used to monitor and benchmark competitor content?",
    "How is scraping used to track media coverage in PR and marketing?",
    "How does scraping inform affiliate product performance tracking?",
    "How does scraping competitor hiring data inform go-to-market strategies?",
    "What are the limitations of using web scraping for marketing analytics?",
    "How do marketers scrape and analyze data from marketplaces like Amazon?",
    "How is scraped data visualized for marketing decision-making?",
    "How does scraping consumer feedback aid in product development?",
    "How do marketers track competitor backlink profiles using scraping?",
    "How is scraping used for sentiment analysis in marketing?",
    "How do companies use scraping to compare distribution channel effectiveness?",
    "How does scraping help in monitoring and analyzing ad creatives?",
    "How is scraped data combined with survey data in market research?",
    "What role does scraping play in understanding customer journeys?",
    "How do scraped insights support brand repositioning efforts?",
    "How do marketers keep scrapers resilient against anti-bot mechanisms?",
    "How can web scraping help monitor trends in user-generated content?",
    "How does scraping competitor blog content help identify content gaps?",
    "What KPIs can be derived from scraped user reviews?",
    "How can scraped data enhance go-to-market strategies?",
    "How do marketers assess data quality from scraped sources?",
    "How is scraping used to monitor product availability across retailers?",
    "How does scraping support omni-channel marketing strategies?",
    "How can scraped customer complaints inform churn reduction strategies?",
    "How can scraping reveal unmet customer expectations?",
    "How is scraping used in account-based marketing (ABM)?",
    "How do companies use scraping to track competitor brand sentiment?",
    "How is scraping used to monitor the effectiveness of seasonal campaigns?",
    "What scraping tools are most popular among marketing teams?",
    "How does scraping inform social listening efforts?",
    "What scraped data types are most useful for marketing funnel optimization?",
    "How is scraping used to validate buyer personas?",
    "How do marketers use scraping to monitor competitor feature releases?",
    "How does scraping support partnership identification in marketing?",
    "How can scraped financial data inform marketing spend decisions?",
    "How do marketers combine scraping with machine learning for predictions?",
    "What metrics do marketers extract from scraped social media data?",
    "How is scraping used to analyze user engagement on competitor websites?",
    "How do marketers ensure scraped data aligns with strategic goals?",
    "What internal stakeholders benefit most from scraped marketing data?",
    "How is scraping used to assess cross-border market potential?",
    "How do marketers use scraping to monitor online reputation?",
    "What are the cost considerations of building vs. buying scrapers for marketing?",
    "How do marketers use scraped data to optimize conversion rates?",
    "What role does scraping play in campaign benchmarking?",
    "How is scraping used in influencer discovery and vetting?",
    "How can scraping help validate product-market fit?",
    "What are common pitfalls marketers face when starting with scraping?",
    "How do scraped job listings inform competitive positioning?",
    "How does scraping support continuous competitor monitoring?",
    "What organizational processes are needed to operationalize scraped data in marketing?"
]


for question in questions:
    token = ""
    analysis_payload = {
        "query": question,
        "review_date_from": "2018-01-01T00:00:00Z",
        "industries": None,
        "company_sizes": None
    }
    headers = {
        "Authorization": f"Bearer {token}"
    }

    analysis_response = requests.post("http://localhost:8000/api/analyze/", json=analysis_payload, headers=headers)
    time.sleep(5)
    print(analysis_response.status_code)